### ISSUE TITLE
Configure runtime constants in chopsticks

### ISSUE THREAD

**Issue by lvndry** [AcalaNetwork/chopsticks#780] opened 2024-06-11 14:12 UTC
Hello,

There's very little documentation how we can configure chopsticks. I'd like to change the `bondingDuration`to `0` so that I can withdraw unbonded amount instantly. 
Could you tell me if or how it can be done ?

**Comment by qiweiii** [comment] 2024-06-11 14:30
may be a duplicate of this issue: https://github.com/AcalaNetwork/chopsticks/issues/594

**Comment by xlc** [comment] 2024-06-12 02:38
The process will be pretty much same as how people change it mainnet. i.e.
- Update the code. in the case of the polkadot runtime: https://github.com/polkadot-fellows/runtimes/blob/5084967a2fc34a2cd6442367fec628ced68c7757/relay/polkadot/src/lib.rs#L685
- Build a wasm
- run with additional flag `--wasm-override path/to/new/polkadot.wasm

**Comment by lvndry** [comment] 2024-06-12 08:53
Okay I was excepting to be able to be able to override this behavior by setting the `dev_storage` or `import-storage` or a RPC call.
My use case is simply that I need to be able to bound and then unbound and withdraw in the same minute. 
Is there a solution that don't require to fork the SDK ?

**Comment by ermalkaleci** [comment] 2024-06-12 09:11
yes, fast forward in the future `dev_newBlock({ unsafeBlockHeight: <future_block> })`

**Closed** 2024-06-13 06:09 UTC
